{% set version = "2.5.1" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: http://download.osgeo.org/postgis/source/postgis-{{ version }}.tar.gz
  sha256: fb137056f43aae0e9d475dc5b7934eccce466f86f5ceeb69ec8b5cea26817a91

build:
  number: 1
  skip: True  # [ win ]

requirements:
  build:
    - {{ compiler('c') }}
    - libxslt
  host:
    - cunit
    - gdal
    - geos
    - gettext
    - pcre
    - proj4
    - json-c
    - perl
    - postgresql
  run:
    - gdal
    - geos
    - gettext
    - pcre
    - proj4
    - {{ pin_compatible('json-c') }}
    - postgresql

test:
  commands:
    - shp2pgsql
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'PostGIS adds geometry, geography, raster and other types to the PostgreSQL database'

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/docs/manual-2.3/
  dev_url: http://svn.osgeo.org/postgis/

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
    - ocefpaf
