{% set version = "3.2.0" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: https://github.com/postgis/postgis/archive/{{ version }}.tar.gz
  sha256: c725d1be6d57ad199bbb6393cc3546defb70de1c78fe1787f7ccef2d51c3647b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - autoconf
    - automake
    - libtool
    - make
    - perl 5.*
  host:
    - libxslt
    - cunit
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq
  run:
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq

test:
  files:
    - test_data
  commands:
    - shp2pgsql test_data/test.shp
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.TXT
  summary: PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/documentation/
  dev_url: https://git.osgeo.org/gitea/postgis/postgis

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
    - xylar
    - mxr-conda
