{% set version = "3.0.0dev" %}
{% set commit = "aafcb2e8ef797be6537f160dc321396a6fb5c8c9" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: https://github.com/postgis/postgis/archive/{{ commit }}.tar.gz
  sha256: 78924daee7e6742fcd10e40ee9d835b0021334c9c670199d36d87505cfe7c723

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - autoconf
    - automake
    - libtool
  host:
    - libxslt
    - cunit
    - libgdal
    - geos
    - gettext
    - pcre
    - proj4
    - json-c
    - perl
    - postgresql
    - libpq
  run:
    - libgdal
    - geos
    - gettext
    - pcre
    - proj4
    - json-c
    - postgresql
    - libpq

test:
  files:
    - test_data
  commands:
    - shp2pgsql test_data/test.shp
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.'

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/docs/manual-2.3/
  dev_url: http://svn.osgeo.org/postgis/

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
