{% set version = "3.0.0" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: https://github.com/postgis/postgis/archive/{{ version }}.tar.gz
  sha256: 1c83fb2fc8870d36ed49859c49a12c8c4c8ae8c5c3f912a21a951c5bcc249123

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - autoconf
    - automake
    - libtool
  host:
    - libxslt
    - cunit
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - perl
    - postgresql
    - libpq
  run:
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq

test:
  files:
    - test_data
  commands:
    - shp2pgsql test_data/test.shp
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.'

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/docs/manual-2.3/
  dev_url: http://svn.osgeo.org/postgis/

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
