{% set version = "3.0.3" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: https://download.osgeo.org/postgis/source/postgis-{{ version }}.tar.gz
  sha256: 07fedbd046cbed55d24bb22474890a4651d0223b6e12d2dac1517b9a43674817

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - autoconf
    - automake
    - libtool
  host:
    - libxslt
    - cunit
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - perl
    - postgresql
    - libpq
    - libxml2
  run:
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq
    - libxml2

test:
  files:
    - test_data
  commands:
    - shp2pgsql test_data/test.shp
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/documentation/
  dev_url: https://git.osgeo.org/gitea/postgis/postgis

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
    - xylar
