{% set version = "3.6.0" %}

package:
  name: postgis
  version: {{ version }}

source:
  url: https://github.com/postgis/postgis/archive/{{ version }}.tar.gz
  sha256: a2308e6b64f48b6985285bdfa40ddeb8eaa0630f3f1fdb92b487d49562fdcafd

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}  # [not win]
    - {{ compiler('cxx') }}
    - pkg-config      # [not win]
    - autoconf        # [not win]
    - automake        # [not win]
    - libtool         # [not win]
    - make            # [not win]
    - m2-bash         # [win]
    - m2-make         # [win]
    - m2-autoconf     # [win]
    - m2-automake-wrapper  # [win]
    - m2-libtool      # [win]
    - perl 5.*
    - libxslt
    - gettext-tools  # [not win]
  host:
    - cunit
    - libgdal-core
    - geos
    - pcre2
    - proj
    - json-c  # [not win]
    - postgresql
    - libpq
    - libxml2
    - m2-liblzma  # [win]
    - liblzma-devel  # [not win]
  run:
    - postgresql

test:
  files:
    - test_data
  commands:
    - shp2pgsql test_data/test.shp
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.TXT
  summary: PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/documentation/
  dev_url: https://git.osgeo.org/gitea/postgis/postgis

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
    - xylar
    - mxr-conda
