# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpostgresql10.4
    - CONFIG=osx_c_compilerclangpostgresql9.6
    - CONFIG=osx_c_compilertoolchain_cpostgresql10.4
    - CONFIG=osx_c_compilertoolchain_cpostgresql9.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NJhgTakFXm8nfsb3GSmYUtEnrqSV0YN9ADjMCKkPJQzLI/yP5KCFtEwWFaFHdUaWpBYkxvarChZyFkdaPXxnQ8d28iGbOredVDvRcewNO28P260+wmW/UnNohkq9t3i/EBVdtrGR2ntND21nx6RlOeSHtG4y2ZxVqomd+WbAXeQZHBS+q+EgvOqeBG8qBk43hjBcLqIkGzkQ6gk3mIsFlI2xrHqw1zPqhKP3ARv4fDrRYFnkk6Ac7Xpdbft0RnqTMYLDXSrBVBrckez6ggkx9McyvXu5KVfsqi4e+3pX98a7eNpUlBj60n27D2wLUo3XNWSQhluSWic5QTglNakwph7iQzdMdaJqK/NUYK+GKXvm7cYswLoxaXsABP/OO8TiV9g+u7I/7c13GCLFiWNiv+TER0Gg6o4ti7veLpbgioq7jpQBYyKZE6Ng23V5keCBSRb9Z/WuHP9Sljm+W+872dZHEQNNhH5XwN8rF7/4TIpqQrso6YE7NPq8dGastTFyRaTfg6otUJXgNLPoXcDeaCBWKzp2AIw9Oy3gMclklvA6cp/94TBnJ5nJcXOHrXe0EsdZ/UR0Rq4TcvQ6qIB4g4pfAnNQbi4E2ti6Blqud9yo4goRXJJPlXFCFCnQS44iK2E3ScHXTJc78suAaoLcYUFVeqQZ180eNeq0vsK0e0k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
