travis:
  secure:
    BINSTAR_TOKEN: NJhgTakFXm8nfsb3GSmYUtEnrqSV0YN9ADjMCKkPJQzLI/yP5KCFtEwWFaFHdUaWpBYkxvarChZyFkdaPXxnQ8d28iGbOredVDvRcewNO28P260+wmW/UnNohkq9t3i/EBVdtrGR2ntND21nx6RlOeSHtG4y2ZxVqomd+WbAXeQZHBS+q+EgvOqeBG8qBk43hjBcLqIkGzkQ6gk3mIsFlI2xrHqw1zPqhKP3ARv4fDrRYFnkk6Ac7Xpdbft0RnqTMYLDXSrBVBrckez6ggkx9McyvXu5KVfsqi4e+3pX98a7eNpUlBj60n27D2wLUo3XNWSQhluSWic5QTglNakwph7iQzdMdaJqK/NUYK+GKXvm7cYswLoxaXsABP/OO8TiV9g+u7I/7c13GCLFiWNiv+TER0Gg6o4ti7veLpbgioq7jpQBYyKZE6Ng23V5keCBSRb9Z/WuHP9Sljm+W+872dZHEQNNhH5XwN8rF7/4TIpqQrso6YE7NPq8dGastTFyRaTfg6otUJXgNLPoXcDeaCBWKzp2AIw9Oy3gMclklvA6cp/94TBnJ5nJcXOHrXe0EsdZ/UR0Rq4TcvQ6qIB4g4pfAnNQbi4E2ti6Blqud9yo4goRXJJPlXFCFCnQS44iK2E3ScHXTJc78suAaoLcYUFVeqQZ180eNeq0vsK0e0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
